import java_cup.runtime.*;

/* Terminales (Tokens devueltos por el Lexer) */
terminal PLUS, MINUS, ASSIGN;
terminal String NUMBER, ID;

/* No terminales (Estructuras de la gramática) */
non terminal program, equation_list, equation, expression;

/* Precedencia de operadores para evitar ambigüedades */
precedence left PLUS, MINUS;

/* Regla inicial */
program ::= equation_list ;

/* Una lista puede tener una o varias ecuaciones */
equation_list ::= equation_list equation
                | equation ;

/* Una ecuación es una expresión igualada a otra expresión */
equation ::= expression ASSIGN expression ;

/* Reglas de lo que compone una expresión */
expression ::= expression PLUS expression
             | expression MINUS expression
             | ID
             | NUMBER ;
